// Everything the app pages say. Edit here, then `node build.mjs`.
//
// Store links: set `url` once an app is live in that store. Until then the
// button shows "Coming soon" instead of linking to a page that does not exist.

export const apps = [
  {
    slug: 'calamus3',
    name: 'Calamus3',
    icon: '/assets/img/calamus3.png',
    tagline: 'Private messaging, end-to-end encrypted.',
    summary:
      'Chat one-to-one and in groups with messages encrypted on your phone. No phone number, no email — just a username.',
    platforms: 'Android',
    stores: {
      play: { url: null, id: 'com.thequreshico.calamus3' },
      appStore: { url: null, note: 'iPhone version not available yet' },
    },
    storeNote: 'Calamus3 is in testing on Google Play and will be available to everyone soon.',
    features: [
      ['End-to-end encrypted', 'Messages are encrypted with the Signal Protocol and kept on your phone, not our servers.'],
      ['No phone number', 'Sign up with a username and password. We never ask for your number or email.'],
      ['Groups and calls', 'Group chats by invitation, plus voice and video calls between two people.'],
      ['Make it yours', 'Themes, profile pictures and privacy controls for who sees you online.'],
    ],
    faqs: [
      ['Is Calamus3 free?', 'Yes. Creating an account and messaging are free.'],
      ['Do I need a phone number or email address?',
        'No. You create an account with a username, a password and a recovery password. There is nowhere in the app to enter a phone number or email address.'],
      ['Can anyone else read my messages?',
        'No. Messages are end-to-end encrypted on your phone before they are sent. Our servers only pass the encrypted message along and delete it once it is delivered — we cannot read it.'],
      ['I forgot my password. How do I get back in?',
        'Use "Forgot password" on the sign-in screen and enter your recovery password. Because there is no email on your account, the recovery password is the only way back in — keep it somewhere safe.'],
      ['What happens to my chats if I lose or change my phone?',
        'Chats live on your phone. Turn on Chat backup in Settings and keep the recovery code it gives you; with that code you can restore your chats on a new phone. Without it, nobody — including us — can recover them.'],
      ['Can I use one account on two phones?',
        'No. An account is used on one phone at a time. Signing in on a new phone moves your account there, and the old phone signs out and removes its chats.'],
      ['Is there an iPhone version?', 'Not yet. Calamus3 is available for Android first.'],
      ['How do I delete my account?',
        'Open Settings in the app and choose Delete account. Your account and profile are removed from our servers.'],
    ],
    howTo: [
      ['Create your account', 'Choose a username, a password and a recovery password. Write the recovery password down — it is the only way to reset your password.'],
      ['Add your contacts', 'Open the Contacts tab and tap Add contact. Search for a username, browse Discover, or share your profile so friends can add you.'],
      ['Start a chat', 'In the Chats tab, tap + and choose New message for a one-to-one chat or New group to invite several contacts.'],
      ['Turn on Chat backup', 'In Settings, turn on Chat backup and save the recovery code. It lets you restore your chats if you change phones.'],
      ['Check the security code', 'Open a chat and compare the security code with your contact in person to confirm nobody is in the middle.'],
      ['Personalise', 'Pick a theme, add a profile picture, and choose who can see when you are online in Settings → Privacy.'],
    ],
    policy: 'calamus3.html',
    policyUpdated: 'Last updated 29 September 2026',
  },
  {
    slug: 'adaptiveplanner',
    name: 'AdaptivePlanner',
    icon: '/assets/img/adaptiveplanner.png',
    tagline: 'A planner that reorganizes itself when plans change.',
    summary:
      'Tasks move around your meetings, prayer times and deadlines automatically — no more shuffling your day by hand.',
    platforms: 'Android and iPhone',
    stores: {
      play: { url: null, id: 'ca.thequreshico.adaptiveplanner' },
      appStore: { url: null },
    },
    storeNote: 'AdaptivePlanner is launching soon on Google Play and the App Store.',
    features: [
      ['Plans around your calendar', 'Reads your phone’s calendars so meetings block time — and never changes them.'],
      ['Adapts when you run over', 'At the end of a task choose Done, Extend or Reschedule, and the rest of your day follows.'],
      ['Respects your prayers', 'Optional prayer and worship times are protected and never scheduled over.'],
      ['No account needed', 'Start planning straight away. Create an account only if you want a backup.'],
    ],
    faqs: [
      ['Do I need to create an account?',
        'No. The app works as soon as you open it. Creating an account is optional and only needed to back up your plans or use them on another phone.'],
      ['Will AdaptivePlanner change my calendar?',
        'No. It only reads your calendars so your meetings block time in your plan. Calendar events are read on your phone and are never uploaded.'],
      ['What happens when a task runs over?',
        'When a task’s time is up, the app asks whether you are done. Choose Done, Extend (by 15, 30, 45 or 60 minutes, or any amount) or Reschedule, and everything after it moves to fit.'],
      ['Does it use AI?',
        'No. The planner follows clear rules that run on your phone: tasks go into your free time, around meetings and prayers, before their deadlines and after the tasks they depend on.'],
      ['How do prayer times work?',
        'If you choose to, set your religion and calculation method in Settings. Prayer or worship times are calculated for your location and kept free. Tap a prayer on the Home screen to move it later within its allowed time on a particular day.'],
      ['Is there a home-screen widget?',
        'Yes, on Android. It shows your current task, your next free time and the rest of today.'],
      ['How do I delete my data?',
        'Go to Settings → Profile → Delete account (or Erase all my data if you never created an account). Everything is deleted straight away.'],
    ],
    howTo: [
      ['Open the app', 'There is no sign-up screen — you can start planning immediately.'],
      ['Set your working hours', 'In Settings → Schedule, choose when your day starts and ends. Tasks are only placed inside these hours.'],
      ['Connect your calendars', 'In Settings → Calendars, choose which of your phone’s calendars should block time.'],
      ['Add tasks', 'Tap + and give each task a name, how long it takes, its energy level and, if it has one, a due date.'],
      ['Answer the reminder', 'When a task ends, tap Done, Extend or Reschedule. Your day re-plans itself around the answer.'],
      ['Optional: prayer times', 'In Settings, set your religious observance so prayer or worship times are protected in your plan.'],
    ],
    policy: 'adaptiveplanner.html',
    policyUpdated: 'Effective 1 October 2026',
  },
  {
    slug: 'granteez',
    name: 'Granteez',
    icon: null,
    monogram: 'G',
    tagline: 'Grant funding, without the guesswork.',
    summary:
      'Granteez finds the grants your nonprofit actually qualifies for and drafts a first application grounded in your own documents.',
    platforms: 'For nonprofit organizations',
    stores: {
      play: { url: null },
      appStore: { url: null },
    },
    storeNote: 'Granteez is in development. Contact us to hear when it launches.',
    features: [
      ['Discover', 'Finds grants, sponsorships and funding programs that match your mission, programs and location.'],
      ['Draft', 'A complete first draft, written only from your own uploaded documents, with every claim cited to its source.'],
      ['Approve & submit', 'Your team reviews and approves with a second sign-in step, with a record of who approved what.'],
      ['Your data, protected', 'Documents are encrypted per organization and never used to train anything.'],
    ],
    faqs: [
      ['Who is Granteez for?',
        'Nonprofits and charities — especially small teams without a full-time grant writer.'],
      ['Does Granteez make things up in the application?',
        'No. Drafts are written only from the documents your organization uploads, and every claim is cited back to its source so your team can check it.'],
      ['How does pricing work?',
        'A straightforward fee per application, charged only when you choose to unlock a draft. There are no seat licences to negotiate.'],
      ['Will you use our documents to train AI?',
        'No. Your documents are encrypted for your organization alone, are never shared with other organizations and are never used for training.'],
      ['Does Granteez submit applications on its own?',
        'No. Nothing goes out until someone on your team approves it, and approving requires a second sign-in step.'],
    ],
    howTo: [
      ['Create your organization', 'Sign up, invite your teammates and set up two-step sign-in.'],
      ['Complete your profile', 'Describe your mission, programs and where you work, so matches fit.'],
      ['Upload your documents', 'Add the reports, budgets and program descriptions a funder would ask about.'],
      ['Review your matches', 'Each opportunity is scored against your profile, so you can focus on the ones worth applying to.'],
      ['Unlock and edit the draft', 'Unlock an application to see its full, cited draft, then review and edit it with your team.'],
      ['Approve and submit', 'Approve with your second sign-in step when the application is ready to go.'],
    ],
    policy: null,
    policyUpdated: null,
  },
];
